AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  AlertMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/alert-message.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that send a email.
      Events:
        AlertMessageApi:
          Type: Api
          Properties:
            Path: /
            Method: GET
      Policies:
      - SNSPublishMessagePolicy:
          TopicName:
            Fn::GetAtt:
            - AlertMessageTopic
            - TopicName
      Environment:
        Variables:
          SNS_TOPIC_ARN:
            Ref: AlertMessageTopic
      CodeUri: s3://falldetector-01/dcce8c6cdbc78fc6dd9262ea53b3b61c
  AlertMessageTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: constanzajazme@gmail.com
        Protocol: email
