AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs12.x
    MemorySize: 128
    Timeout: 100

Resources:
  AlertMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/alert-message.EmailAlerthandler
      Description: A Lambda function that send a email.
      Events:
        AlertMessageApi:
          Type: Api
          Properties:
            Path: /
            Method: GET
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt AlertMessageTopic.TopicName
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref AlertMessageTopic

  AlertMessageTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: constanzajazme@gmail.com
          Protocol: email

  AlertPhoneFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/alert-message.PhoneAlerthandler
      Description: A Lambda function that send a SMS.
      Events:
        AlertPhoneApi:
          Type: Api
          Properties:
            Path: /sender
            Method: POST
      Policies:
        - AWSLambdaBasicExecutionRole
