AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs12.x
    MemorySize: 128
    Timeout: 100

Resources:
  AlertMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/alert-message.EmailAlerthandler
      Description: A Lambda function that send a email.
      Events:
        AlertMessageApi:
          Type: Api
          Properties:
            Path: /
            Method: GET
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt AlertMessageTopic.TopicName
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref AlertMessageTopic

  AlertMessageTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: constanzajazme@gmail.com
          Protocol: email

  AlertPhoneMessageFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Description: A Lambda function that send a SMS.
      Handler: src/handlers/alert-message.PhoneAlertHandler
      Runtime: nodejs12.x
      Events:
        AlertPhoneMessage:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get